---
name: kig
version: 17.08.1
summary: Explore Geometric Constructions
description: Kig is an interactive mathematics software for learning and teaching
    geometry. It allows to explore mathematical figures and concepts using the computer
    and also can serve as a drawing tool for mathematical figures. Constructions can
    be made with points, vectors, lines, and polygons and all elements can be modified
    directly by using the mouse. Kig helps teachers and students to make conjectures
    and to understand how to prove geometric theorems.
confinement: strict
grade: stable
apps:
    kig:
        command: kf5-launch kig
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kig
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kig:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libboost-python-dev
        - libkf5kdelibs4support-dev
        - pkg-config
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kig-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
